# Generated by Django 5.1.5 on 2025-02-04 16:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqn4oyjlv/image/upload/v1738684919/default-poster_hjhwj4.webp', max_length=255, verbose_name='poster'),
        ),
    ]
