# Generated by Django 5.1.5 on 2025-02-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screening_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
