# Generated by Django 5.1.5 on 2025-02-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='movie',
        ),
    ]
